### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by danghica** [lives-group/red-black-trees-agda#1]
Hello,

I would like to user your code in a module I teach on Agda at the University of Birmingham. 

May I?

Regards,
Dan

**Comment by rodrigogribeiro** [comment]
Dear Dan Ghica,

Thanks for your message! Feel free to use the code as you want.

Best regards,

Rodrigo

PS: Sometime ago, I've  read some of our papers on the usage of linear
types for resource control: a really nice work!

**Comment by danghica** [comment]
Thank you! On both accounts :)
